title: "M.D. Walters' Blog!"
author: "M.D. Walters"
description: "Inside the world of M.D."

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

timezone: America/New_York

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: other
