title: "M.D. Walters' Blog!"
author: "M.D. Walters"
description: "Inside the world of M.D."

remote_theme: pages-themes/hacker@v0.2.0

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: other
